pillar.example

JUst fixes a small typo in a comment as a first pull request

fix comment typo

---

README.rst
php/apcu.sls
php/map.jinja
php/ng/apcu.sls
php/ng/map.jinja

APC is kind of useless since opcache is now the standard, but APCU which contains the user cache functions only is still quite nice to have

Add apcu support

---

php/ng/map.jinja
php/ng/xsl.sls

Add php.ng.xsl for Debian (php5-xsl package)

Add php.ng.xsl for Debian

---

README.rst
php/ng/hhvm/config.sls
php/ng/hhvm/init.sls
php/ng/hhvm/install.sls
php/ng/hhvm/repo.sls
php/ng/hhvm/service.sls
php/ng/map.jinja

This will add hhvm support to php ng formula, hhvm,  php-fpm is already in here so I like to include in this formula.

Add hhvm support to php ng formula

---

php/ng/files/php.ini

php ini files can be quite large and sorting the keys here makes it a lot easier to find what you are looking for

Sort keys per section within php.ini.

---

php/ng/installed.jinja

regarding https://github.com/saltstack-formulas/php-formula/issues/61, checks value, defaulting to false on absence.

use False as default, and test boolean, rather than none

---

php/ng/map.jinja
php/ng/opcache.sls

Added opcache package for CentOS. Tested on CentOS7.

Add opcache package for CentOS

---

php/ng/map.jinja

Added same logic to  php:ng formula for debian php 7.0 release
plus minor improvements to archlinux php cli.

Update php ng map with debian php 7.0

---

php/ng/composer.sls
php/ng/map.jinja

Add composer package as it is available from EPEL repositories.
Tested on CentOS 7.

Add composer package

---

php/ng/installed.jinja

Fixing broken code from https://github.com/saltstack-formulas/php-formula/pull/72
See https://github.com/saltstack-formulas/php-formula/issues/88

Fix for broken test statement that prevents PPA workaround executing

---

php/ng/map.jinja

This fixes archlinux support for php:ng

update map.jinja with removed archlinux and fpm support

---

README.rst
php/ng/cache-lite.sls
php/ng/console-table.sls
php/ng/ffmpeg.sls

oops missed some files with the other pr.

add missing sls files and readme

---

php/bcmath.sls
php/ng/bcmath.sls
php/ng/map.jinja

Add the php-bcmath package to Ubuntu 16.04 and Debian 7

add php-bcmath

---

pillar.example

I had to dig through the source to figure this out.  Will need to be updated again once #116 is merged.

Update pillar.example to reflect new structure

---

php/ng/cli/install.sls
php/ng/installed.jinja

Added external sury repo for debian machines not only ubuntu ppa's
fixed cli installed state.

add sury repo for debian machines

---

php/ng/cli/ini.sls
php/ng/fpm/config.sls
php/ng/fpm/pools_config.sls
php/ng/xcache/ini.sls

python3 deprecated iteritems, fixed with replacing it with items()

fix iteritems for python3

---

README.rst

I added a bunch of missing modules to the readme and re-alphabetized them

Updated readme with missing modules

---

php/ng/xmlwriter.sls

Added `php/ng/xmlwriter.sls`
Added new line at end of file  `php/ng/simplexml.sls`

fix(mods): fixup for #181

---

.travis.yml
kitchen.yml
test/integration/default/controls/package_spec.rb
test/salt/pillar/suse.sls

* Automated using https://github.com/myii/ssf-formula/pull/16

ci(kitchen+travis): replace EOL pre-salted images

---

php/map.jinja

The PID file location for Debian changed recently
see https://www.patreon.com/posts/february-updates-34189046
and https://github.com/oerdnj/deb.sury.org/issues/1334
---
No.

fix(map.jinja): fix pid file location for debian

---

.pre-commit-config.yaml
.travis.yml
php/_mapdata/_mapdata.jinja
php/_mapdata/init.sls
test/integration/default/controls/_mapdata_spec.rb
test/integration/default/files/_mapdata/amazonlinux-1.yaml
test/integration/default/files/_mapdata/amazonlinux-2.yaml
test/integration/default/files/_mapdata/centos-7.yaml
test/integration/default/files/_mapdata/centos-8.yaml
test/integration/default/files/_mapdata/debian-10.yaml
test/integration/default/files/_mapdata/debian-9.yaml
test/integration/default/files/_mapdata/fedora-30.yaml
test/integration/default/files/_mapdata/fedora-31.yaml
test/integration/default/files/_mapdata/opensuse-15.yaml
test/integration/default/files/_mapdata/ubuntu-16.yaml
test/integration/default/files/_mapdata/ubuntu-18.yaml

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/284

refactor(map): use top-level `values:` key in `map.jinja` dumps

---

php/_mapdata/init.sls
test/integration/default/files/_mapdata/amazonlinux-1.yaml
test/integration/default/files/_mapdata/amazonlinux-2.yaml
test/integration/default/files/_mapdata/centos-7.yaml
test/integration/default/files/_mapdata/centos-8.yaml
test/integration/default/files/_mapdata/debian-10.yaml
test/integration/default/files/_mapdata/debian-9.yaml
test/integration/default/files/_mapdata/fedora-30.yaml
test/integration/default/files/_mapdata/fedora-31.yaml
test/integration/default/files/_mapdata/opensuse-15.yaml
test/integration/default/files/_mapdata/ubuntu-16.yaml
test/integration/default/files/_mapdata/ubuntu-18.yaml

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/287

fix(_mapdata): ensure map data is directly under `values`

---

.github/workflows/kitchen.vagrant.yml
Gemfile
Gemfile.lock
kitchen.vagrant.yml
kitchen.yml
php/composer.sls
php/map.jinja
pillar.example
test/integration/default/controls/config_spec.rb
test/integration/default/controls/package_spec.rb
test/integration/default/controls/service_spec.rb
test/integration/default/files/_mapdata/freebsd-11.yaml
test/integration/default/files/_mapdata/freebsd-12.yaml
test/salt/pillar/freebsd.sls

---
No.
–
On FreeBSD, when using PHP 7.4, there's no package `php74-hash` available. When using PHP 7.2, `php72-hash` *must* be installed.
See `php:lookup:composer` in `pillar.example`.
–

feat(composer): make dependencies configurable

---

php/composer.sls

---
No.
Resolves https://github.com/saltstack-formulas/php-formula/issues/219

fix(composer): stop hanging by preventing interaction

---

docs/README.rst

---
No.
Missing bits of https://github.com/saltstack-formulas/php-formula/pull/234

feat(modules): add missing `zlib` `php` module
