saltstack-formulas/php-formula

php/ng/apache2/ini.sls
php/ng/apache2/init.sls
php/ng/apache2/install.sls
php/ng/map.jinja

This adds php.ng.apache2 to manage libapache2-mod-php5 and /etc/php5/apache2/php.ini
This is almost identical to the php.ng.cli state.

add libapache2-mod-php5 options on debian only

---

README.rst
php/composer.sls
php/map.jinja

Added php.composer which contains much of the same SLS suggested by the composer salt state at http://docs.saltstack.com/en/latest/ref/states/all/salt.states.composer.html
In addition to that, I added `cmd: update-composer` which will run `composer selfupdate` if it is out-of-date.
Presently the check for "is out of date" is hackish, because Composer doesn't give us any way to check it by version compares, but it's functional.  Ideally they would add some visibility into the question of "is composer outdated" and we could then upgrade that piece.
Anyway it made a lot more sense to me for this to live in php-formula rather than having to cut/paste a wall of text into every salt project that wants to use composer, so here it is.

Add php.composer state

---

php/ng/gmp.sls
php/ng/map.jinja

GMP is an extension used for dealing with huge numbers that PHP cannot support by default

Add support for GMP ext

---

php/composer.sls
php/map.jinja

Curl seems like an unnecessary dependency when the Composer installer already has the necessary options to download the composer binary to a specified directory and file name.
file.managed does require a source_hash of the installer file, *not the composer binary*, but that can be updated in the map.jinja file or overridden in the pillar data. As well as being able to set the composer binary file name in the pillar data.

Update Composer state file to not use curl

---

php/map.jinja
php/ng/map.jinja

XML module is already built-in. In any case, `php5-xmlrpc` package actually provides XML-RPC module.

Fix Debian package name for `php.ng.xml` state

---

php/ng/cli/ini.sls
php/ng/fpm/config.sls

Options under `php.fpm.config.ini.settings` and `php.cli.ini.settings` should be merged with `php.ini.defaults`

Recursively merge php.ini options

---

php/composer.sls

If the initial run of `install-composer` fails it will not be attempted again until `get-composer` changes states, which in this case means it will not be attempted again until `/tmp/installer` is removed.
Similarly, if `{{ php.composer_bin }}` or `{{ php.local_bin }}` are changed, composer would not be installed again to reflect these changes in the pillar data.
This pull request resolves this issue by switching to cmd.run and relying on an unless condition to prevent unnecesary execution of `install-composer`.

Fix install-composer edge cases

---

php/ng/map.jinja

regarding https://github.com/saltstack-formulas/php-formula/issues/65
only tested on Ubuntu 14.04.

changed Debian hhvm PID filepath to match default /etc/init.d/hhvm PID filepath

---

php/ng/installed.jinja

This is a work-around #69 which is being caused by saltstack/salt#23543 due to UTF-8 characters appearing in the PPA creator's name.  The solution is taken from @RyPeck, but is not really ideal because it adds a commented deb-src line to the .list file each time the state is run.

Manually add php PPA in UTF-8 locale [Resolves #69]

---

php/ng/installed.jinja

This comit is in addition to pull request #70. The add-apt-repository command
will only be run when the ppa has not yet been added.

Only add ppa if it doesn't exist.

---

php/composer.sls

The composer installer has to be executed with PHP itself as detailed on
https://getcomposer.org/download/.

Run composer installer with PHP

---

php/map.jinja

We probably want to address the underlying issue (i.e. checksum checking) in the future, but this allows installations to continue for now.

Update composer installer sha256 hash

---

php/ng/map.jinja

Added default values based on comment: https://github.com/saltstack-formulas/php-formula/issues/47#issuecomment-174576699
This commit fixes: https://github.com/saltstack-formulas/php-formula/issues/47
Tested on CentOS7

Add default pools values

---

php/composer.sls

Without this installation and updates fail with:
The HOME or COMPOSER_HOME environment variable must be set for
composer to install correctly

Explicitly set HOME when running composer install.

---

php/composer.sls
php/map.jinja

This allows composer installs to function even if the installer checksum
changes, and doesn't force us to update the formula all the time.
We can do this now as composer upstream provides the checksum on
https://composer.github.io/installer.sig since 2016-04-28.
See https://composer.github.io/pubkeys.html for further details.

Do not hardcode composer checksum

---

php/ng/map.jinja
php/ng/tidy.sls

I've added support for the tidy-module (currently only arch tested). Also I added a missing mapping for the geoip module in arch linux

support for tidy module, more support for arch-linux

---

php/ng/map.jinja

debian stretch has renamed php5-apcu into php-apcu.

add php-apcu for debian stretch (7.0)

---

README.rst
php/ng/gearman.sls
php/ng/map.jinja

This PR adds ``php5-gearman`` support for Debian. I'm not sure about other operating systems whether there is such package or no so I didn't add support.
For now there is no php7.0-gearman package in Debian so I didn't add this to ``map.jinja`` too.
If someone knows package names for other systems I could definitely add them to map.jinja.

Add php-gearman support

---

php/ng/map.jinja

Just adding one forgotten package.
I rechecked all packages from [here](https://packages.debian.org/source/sid/php7.0), looks like all extensions we support in formula are now presented in map.jinja

Add intl package name for php7.0

---

php/ng/fpm/pools_config.sls
pillar.example

I need this for the mongo ext_pillar.
https://rene.jochums.at/howto-move-saltstack-tops-and-pillar-contents-to-mongodb
https://rene.jochums.at/having-fun-with-saltstack-and-ext_pillar-mongo
Signed-off-by: Rene Jochum <rene@jochums.at>

Allow overwriting the fpm pools config name via 'filename'.

---

php/map.jinja

This was introduced in #86 and really should have never been released.

Remove duplicate `dev_pkg` entries.

---

php/init.sls

The included state was never submitted in #77 and we therefore 
remove inclusion here to allow users to use the php state again.
This should fix #99

Remove dotdeb from php state

---

php/ng/map.jinja

Tested on Fedora 25. I don't know if the package exists on CentOS / RHEL and if it does, if it has the same name.

Add xdebug package for RedHat family operating systems in map.jina

---

php/ng/map.jinja

Installation on Debian Jessie was not working properly with PHP7.0 packages from https://deb.sury.org/ until we changed this. The map.jinja basically seems a bit messed up, note this is not a cleanup for that file but it made things working again for us.

Improvements to php/ng/map.jinja

---

php/fpm.sls

Including php in php.fpm makes it hard to use php fpm with webservers such as
nginx or lighttpd on, at least, Debian and derivatives.
This fixes #124.

Do not include php state in php.fpm

---

php/ng/cli/install.sls
php/ng/installed.jinja

There is already the Pull-Request #119  and this PR is the alternative mentioned in the PR:
move the state from installed.jinja into cli/install.sls
I just tested this with upgrading from php5.6 to 7.1 on Ubuntu Xenial. With this Patch it works installing php.ng.fpm and php.ng.composer on the same machine :-)

Move state php_{{ phpng_version }}_link to cli/install.sls 

---

php/ng/cli/install.sls
php/ng/installed.jinja

Reverts saltstack-formulas/php-formula#129
not working missing:
{% set phpng_version = salt['pillar.get']('php:ng:version', '7.0')|string %}
{% set current_php = salt['alternatives.show_current']('php') %}

Revert "Move state php_{{ phpng_version }}_link to cli/install.sls "

---

php/ng/fpm/config.sls

This is nice to be able to use the Remi Repository in RedHat family OSs because php-fpm in remi repository doesn't create the ``/etc/php-fpm.d/`` folder where the pools should be.

Fix to be able to create the pools folder in the fpm

---

php/ng/fpm/pools_config.sls
php/ng/map.jinja
pillar.example

Since php5 installs in different location, this formula was not working. I added an if statement to determine the correct dir.
This change only affects Debian with php5.

Make php.ng.maps.jinja work for php5 on Debian

---

php/composer.sls
php/ng/composer.sls

Changed update-composer method to get version date from --version output of composer.
The old method always runs a update because COMPOSER_DEV_WARNING_TIME is only defined after 60days and causes test to fail condition with null value.

Changed method to detect if composer self-update is needed.

---

php/ng/files/php.ini

As per https://github.com/saltstack/salt/issues/39009 - and the following error message:
```
ID: php_fpm_pool_conf_0                                                                                          
Function: file.managed                                                                                                 
Name: /etc/php/7.2/fpm/pool.d/www.conf                                                                             
Result: False                                                                                                        
Comment: Unable to manage file: Jinja error: '<' not supported between instances of 'OrderedDict' and 'OrderedDict'   
Traceback (most recent call last):                                                                           
File …
```

Remove sorting of php.ini files to support Python3

---

php/ng/installed.jinja

Using the latest version of this repo on Ubuntu 18.04 and installing php.ng with the ppa enabled and php 7.3 as target, I get the following:
```
ID: php_ppa_fpm
Function: pkgrepo.managed
Result: False
Comment: Failed to configure repo 'php_ppa_fpm': _call_apt() got multiple values for keyword argument 'env'
Started: 12:30:59.229400
Duration: 72.24 ms
Changes:
```
I am not sure what causes this, I dug in salt source a bit but couldn't figure it out. Renaming to __env__ or removing the env entirely both make it work.

Remove env from ppa definition

---

php/ng/fpm/pools.sls

Calling `php.ng.fpm.pools` (included by `php.ng.fpm`) fails when there is no pool.
Fix, by not trying to extend if we have nothing to add.

fpm: don't extend pool-dependency if no pool

---

php/ng/map.jinja

Hi!
This PR fixes "Invalidly formatted 'pkgs' parameter." error with php-readline.
Thank you!

Fix "Invalidly formatted 'pkgs' parameter." error with php-readline

---

README.rst
php/ng/modules.sls
pillar.example

Support `php.ng.modules` to call and install pillar-listed modules.
Either call the matching `php.ng.xxx` or directly the package from lookup.

php.ng.modules

---

kitchen.yml

* Automated using `ssf-formula` (v0.1.0-rc.5)

chore: use `semantic-release` cross-formula standard structure

---

pre-commit_semantic-release.sh
release.config.js

* Semi-automated using `ssf-formula` (v0.2.0)
* References:
- https://github.com/saltstack-formulas/php-formula/pull/175#issuecomment-517492613
- https://github.com/saltstack-formulas/php-formula/pull/185#issuecomment-517603898
* Ensure this only runs until `v1.0.0` (done in the script)
---
CC: @n-rodriguez @sticky-note.

fix: update deprecation version number in `semantic-release` run

---

php/ng/cli/ini.sls
php/ng/cli/init.sls
php/ng/cli/install.sls
php/ng/fpm/config.sls
php/ng/fpm/init.sls
php/ng/fpm/pools_config.sls
php/ng/ini.jinja
php/ng/installed.jinja
php/ng/map.jinja
pillar.example

[php/ng] support the use of a list of php versions

---

php/ng/installed.jinja

* Ends up with two `include:` lists when rendered
* Close #188
---
CC: @n-rodriguez @sticky-note.

fix(installed.jinja): remove `include` to prevent conflicting IDs

---

php/ng/map.jinja

This fixes the rendering issue:
[CRITICAL] Rendering SLS 'base:php.ng.fpm.config' failed: Jinja variable 'dict object' has no attribute 'user'
When using multiple php versions, this is issued by "{{ php.lookup.fpm.user }}" from php/ng/fpm/config.sls
Add default users in group in the relevant 'fpm' dict from map.jinja
(this is to set owner and group to 'pool.d' directory).

Fix missing value for php.lookup.fpm.user in multi-php mode

---

.yamllint
pillar.example

* Semi-automated using https://github.com/myii/ssf-formula/pull/59
* https://travis-ci.org/myii/php-formula/builds/594703019#L208-L210
```bash
$ yamllint -s .
./pillar.example
151:30    error    forbidden implicit octal value "0660"  (octal-values)
```

fix(pillar.example): fix `octal-values` violation

---

pillar.example

---
No.
Related to #167 ( [php/ng] support the use of a list of php versions)
Add an example on how to use a specific php version in a fpm pool when using multiple versions
None.

Add example to use a specific php version when using multiple ones

---

CODEOWNERS
kitchen.yml
php/_mapdata/_mapdata.jinja
php/_mapdata/init.sls
test/integration/default/controls/_mapdata_spec.rb
test/integration/default/controls/config_spec.rb
test/integration/default/controls/package_spec.rb
test/integration/default/controls/service_spec.rb
test/integration/default/files/_mapdata/amazonlinux-1.yaml
test/integration/default/files/_mapdata/amazonlinux-2.yaml
test/integration/default/files/_mapdata/centos-7.yaml
test/integration/default/files/_mapdata/centos-8.yaml
test/integration/default/files/_mapdata/debian-10.yaml
test/integration/default/files/_mapdata/debian-9.yaml
test/integration/default/files/_mapdata/fedora-30.yaml
test/integration/default/files/_mapdata/fedora-31.yaml
test/integration/default/files/_mapdata/opensuse-15.yaml
test/integration/default/files/_mapdata/ubuntu-16.yaml
test/integration/default/files/_mapdata/ubuntu-18.yaml
test/integration/share/README.md
test/integration/share/inspec.yml
test/integration/share/libraries/system.rb

---
No.
* Automated using https://github.com/myii/ssf-formula/pull/283
* Prompted by:
- https://github.com/saltstack-formulas/php-formula/pull/214
- https://github.com/saltstack-formulas/php-formula/pull/215
- https://github.com/saltstack-formulas/php-formula/issues/216
- https://github.com/saltstack-formulas/php-formula/issues/217

test(map): verify `map.jinja` dump using `_mapdata` state

---

php/map.jinja
test/integration/default/files/_mapdata/freebsd-12.yaml
test/integration/default/files/_mapdata/freebsd-13.yaml

feat(freebsd): add several `php` modules for `FreeBSD` 
